ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-http-request-title: 요청 예시
:operation-request-body-title: 요청 본문 예시
:operation-http-response-title: 응답 예시
:operation-response-fields-title: 응답 필드 상세설명

[[resources]]
= HashtagMap Admin API Guide

[[resources-instagram]]
== Instagram

[[resources-instagram-scheduler-update]]
=== scheduler 실행

operation::instagram/scheduler/update[snippets='http-request,http-response']

[[resources-kakao]]
== Kakao

[[resources-kakao-scheduler-toggle]]
=== scheduler toggle (ON/OFF)

operation::kakao/scheduler/toggle[snippets='http-request,request-fields,http-response']

[[resources-kakao-scheduler-status]]
=== scheduler 상태 조회

operation::kakao/scheduler/status[snippets='http-request,request-parameters,http-response,response-fields']

[[resources-kakao-scheduler-period-put]]
=== scheduler 주기 변경

operation::kakao/scheduler/period/put[snippets='http-request,http-response']

[[resources-kakao-scheduler-period-get]]
=== scheduler 주기 조회

operation::kakao/scheduler/period/get[snippets='http-request,http-response,response-fields']
[[resources-district]]
== District

[[resources-district-getAllDistrict]]
=== 전체 지역 정보 조회

operation::district/getAllDistrict[snippets='http-request,http-response,response-fields']

[[resources-district-saveDistrict]]
=== 새로운 지역 정보 저장

operation::district/deleteDistricts[snippets='http-request,request-body,http-response,response-fields']

[[resources-district-deleteDistricts]]
=== 선택한 지역 정보 삭제

operation::district/deleteDistricts[snippets='http-request,request-body,http-response,response-fields']

[[resources-district-updateDistrict]]
=== 선택한 지역 정보 수정

operation::district/updateDistrict[snippets='http-request,request-body,http-response,response-fields']

[[resources-tag-levels]]
== TagLevel

[[resources-tag-levels-findAll]]
=== 태그레벨 정보 조회

operation::tag-levels/findAll[snippets='http-request,http-response,response-fields']

[[resources-tag-levels-create]]
=== 태그레벨 생성

operation::tag-levels/create[snippets='http-request,http-response']

[[resources-tag-levels-delete]]
=== 태그레벨 삭제

operation::tag-levels/delete[snippets='http-request,http-response']