spring:
  profiles:
    include: >
      db
    active: local
  datasource:
    hikari:
      pool-name: hashtagmap-pool
      minimum-idle: 5
      maximum-pool-size: 50
      connection-timeout: 3000
      max-lifetime: 1800000
      transaction-isolation: TRANSACTION_REPEATABLE_READ
  jpa:
    open-in-view: false

---
spring:
  profiles: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:hashtagmap;mode=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    generate-ddl: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE