spring:
  profiles:
    include: >
      kakao,
      kakao-security,
      db,
      slack-admin
  mvc:
    view:
      suffix: .html
  jpa:
    open-in-view: false
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
